### ISSUE TITLE
Doesn't pass return value

### ISSUE THREAD

**Issue by olalonde** [wankdanker/node-function-rate-limit#5]
e.g. rateLimitedFn = rateLimit(1, 1000, () => 'test'); console.log(rateLimitedFn())

**Comment by olalonde** [comment]
Just realised this wouldn't really be possible. It would be nice if this module supported promise returning functions though.

**Comment by lpinca** [comment]
@olalonde take a look at https://github.com/lpinca/valvelet

**Comment by olalonde** [comment]
@lpinca thanks
